spring:
  application:
    name: usian-item-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/usian?characterEncoding=UTF-8
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    cluster:
      nodes:
        - 192.168.3.134:7001
        - 192.168.3.134:7002
        - 192.168.3.134:7003
        - 192.168.3.134:7004
        - 192.168.3.134:7005
        - 192.168.3.134:7006
    jedis:
      pool:
        min-idle: 5
        max-active: 20
        max-idle: 10
  rabbitmq:
    host: 192.168.3.137
    username: admin
    password: 1111
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
#配置缓存首页商品分类
PROTAL_CATRESULT_KEY: PROTAL_CATRESULT_KEY
#商品详情
ITEM_INFO: ITEM_INFO
BASE: BASE
DESC: DESC
PARAM: PARAM
ITEM_INFO_EXPIRE: 86400
#分布式锁
SETNX_BASC_LOCK_KEY: SETNX_BASC_LOCK_KEY
SETNX_DESC_LOCK_KEY: SETNX_DESC_LOCK_KEY
SETNX_PARAM_LOCK_KEY: SETNX_PARAM_LOCK_KEY

